### ISSUE TITLE
update pub.dev version to newest master

### ISSUE THREAD

**Issue by BujusKrachus** [biocarl/drawing_animation#35]
Currently the version 1.0.1 on pub.dev will not work with newer flutter versions or newer flutter packages in particular, due to the xml version, which got luckily bumped already in f78e785933774533d207c67d4f3728ee7ca4d8a6. Unfortunately this change is not yet on pub.dev, please update @biocarl if you find some time.

For other readers: Use this in your `pubspec.yaml`:
```
  drawing_animation:
    git:
      url: https://github.com/biocarl/drawing_animation.git
      ref: f78e785933774533d207c67d4f3728ee7ca4d8a6
```
